# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00d741153818dda7fedd2a02e3b6023f"
name = "taxid-companyname-checkout"
handle = "taxid-companyname-checkout-1237"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-9b397d60.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
